### PR TITLE
PLF-6590 Disable useless JCR actions for Social WS

### PR DESCRIPTION
**Pull request by boubaker**
Some JCR actions are useless and generates a lot of items in JCR:
org.exoplatform.services.jcr.ext.owner.AddOwneableAction
org.exoplatform.services.cms.jcrext.AddDateTimeAction
org.exoplatform.services.cms.jcrext.ModifyNodeAction
org.exoplatform.services.cms.jcrext.AddNodeNameAction

Those actions are disabled on Social except for "ModifyNodeAction" and "AddDateTimeAction" for nodeType "soc:spaceref"

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
The PR looks good. Just a question about the actions on soc:spaceref : are the mixins added on this node type necessary for the product directly ? I remember the Community team said they use some mixins in their project. I just want to be sure that we do not include something specific to the Community project in the product.

**Comment by boubaker** [comment]
It's used in the product to determine the last accessed spaces by a user and to determine if the space is accessed before:
https://github.com/exoplatform/social/blob/develop/component/core/src/main/java/org/exoplatform/social/core/storage/impl/SpaceStorageImpl.java#L1963
https://github.com/exoplatform/social/blob/develop/component/core/src/main/java/org/exoplatform/social/core/storage/impl/SpaceStorageImpl.java#L2095

**Comment by thomasdelhomenie** [comment]
Ok good, thanks.

**Comment by thomasdelhomenie** [comment]
Merged

**Pull request closed without merging**
