### PR TITLE
PLF-6762: [Regression]: Wrong home page when connecting to platform

### PR DESCRIPTION
**Pull request by kmenzli**

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
It works fine but with this configuration, the dependency eXoSkin is also the last one, even with the Chat addon install. I guess it can be a problem in the case a customer created a new skin, it must be after eXoSkin. eXoSkin should have a lower priority. WDYT ?

**Comment by kmenzli** [comment]
This is why I have changed the configuration in platform-ui project to put eXoSkin extension loaded just after eXoRessources (allows developpers to override styles and add their own look&feel)
**Note** : skin-addon-config.jar is never embedded in plf bundles, and we used platform configuration to declare **eXoSkin** as a dependency in **platform-extension-config.jar**. With your commit https://github.com/exodev/platform-ui/commit/a5d580e660639aab47d2a46b3d8f8b83a007cc12 eXoSkin had become itself an extension, thus, eXoSkin will be considered  twice by **PortalContainerConfig**

- First time as a dependency declared in platform-extension-config.jar

- Second time as an extension declared in eXoSkin.war/META-INF/exo-conf/configuration.xml

**Comment by thomasdelhomenie** [comment]
Ok so you propose to remove eXoSkin.war/META-INF/exo-conf/configuration.xml ? If so, let's go :)

**Comment by kmenzli** [comment]
It it a solution 
Ok I'll update PRs

**Comment by thomasdelhomenie** [comment]
LGTM

**Pull request closed without merging**
