### PR TITLE
PLF-6116 Could not enter search key words fluently in the Search Spac…

### PR DESCRIPTION
**Pull request by trongtt**
…es input

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
I did a test, everything seems to work fine, but when I start typing, the filtered list of spaces does not have any avatar. The JSON response always contains an empty avatarUrl. Example :
```
[{"avatarUrl":{},"displayName":"Platform 5","id":"d25ec2b07f0001016d2c35db3c974851"},{"avatarUrl":{}
,"displayName":"Platform 4","id":"d25e99527f0001016fa5348910de84d5"}]
```

**Comment by trongtt** [comment]
Strange,

In my test, if _avatarUrl_ will not be returned (understand as NULL) if space avatar is not set. Example:
```
[{"avatarUrl":"/rest/jcr/repository/social/production/soc%3Aproviders/soc%3Aspace/soc%3Aspace_2/soc%3Aprofile
/soc%3Aavatar/?upd=1459669338364", "displayName":"Space 2","id":"db068c35c0a801036d2045c4f5b129c0","url"
:"portal/g/:spaces:space_2/space_2"},
{"displayName":"Space 1","id":"d7c564d4c0a80103198a35b519ebe1b8","url":"portal/g/:spaces:space_1/space_1"}]
```

Anyway, I will ask other to double check again.

**Comment by nttuyen** [comment]
I tested on Ubuntu/Jdk 8 and I got the result same as @trongtt, avatarUrl is not returned if space avatar is not set
`[{"avatarUrl":"/rest/jcr/repository/social/production/soc%3Aproviders/soc%3Aspace/soc%3Aspace_2/soc%3Aprofile/soc%3Aavatar/?upd=1459738268253","displayName":"space 2","id":"df284f737f00010167a58cc0d1a8fd9d","url":"portal/g/:spaces:space_2/space_2"},{"displayName":"space 1","id":"df27f3467f00010162b09ba74ed90ebe","url":"portal/g/:spaces:space_1/space_1"}]`

**Comment by thomasdelhomenie** [comment]
I did a new try with your 2 commits and I still have the same issue. I am testing on Ubuntu/JDK 8, with PLF 4.3.x.
I will try with PLF 4.4.x.

**Comment by thomasdelhomenie** [comment]
It works fine with PLF 4.4.x on my side. Did you test with PLF 4.3.x ?

**Comment by trongtt** [comment]
No, I didn't test on PLF 4.3.x. I'm going to check

**Comment by trongtt** [comment]
Very strange, it works fine for me on stable/4.3.x branches.

**Comment by trongtt** [comment]
Anyway, I make a new commit to workaround for the case of an empty object returned. Could you please re-test ?

**Comment by thomasdelhomenie** [comment]
I did a new test with a fresh PLF 4.3.1-M07 and it works fine. So I think you can remove your last commit. My bad.
Then I consider the PR as validated. :+1:

**Comment by trongtt** [comment]
Merged.

**Pull request closed without merging**
