### PR TITLE
WIKI-1322 Add GWT locale metadata

### PR DESCRIPTION
**Pull request by boubaker**
Set GWT base applications locale switch user choosed locale from eXo

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
@boubaker well done !

Since this parameter is only related to wiki, can't we use metaInformation injected in wiki app instead (https://github.com/exodev/platform/pull/282/files#diff-fc1592c8ffacef6b30e08e8a512905dbR138) ?

Also there are still some untranslated strings in the popup which allows to insert macros, but if it is not straightforward I think we can do it in another issue.

**Comment by boubaker** [comment]
> Since this parameter is only related to wiki, can't we use metaInformation injected in wiki app instead

This metadata is generic to any application based on GWT. I think it' better to keep it generic to ensure the automatic integration.

> Also there are still some untranslated strings in the popup which allows to insert macros, but if it is not straightforward I think we can do it in another issue.

Yep, for sure, the description of Macros is a different issue ;-)

**Comment by thomasdelhomenie** [comment]
> This metadata is generic to any application based on GWT. I think it' better to keep it generic to ensure the automatic integration.

That's why it is better to set it when a GWT app is on the page IMO.

> Yep, for sure, the description of Macros is a different issue ;-)

Still about translations, but yes, let's open a new issue for that.

**Comment by boubaker** [comment]
> That's why it is better to set it when a GWT app is on the page IMO.

I don't understand why ?
In addition to add it in portlet rendering phase, the portlet shouldn't have the portlet cache enabled on it (which should be independant)

**Comment by boubaker** [comment]
> Still about translations, but yes, let's open a new issue for that.

It's about third party library translation but not internationalisation integration with the third party library

**Comment by boubaker** [comment]
ok, no need to explain more, I 'll make changes anyway

**Pull request closed without merging**
