### PR TITLE
PLF-7897 tune default value of wakeupInterval

### PR DESCRIPTION
**Pull request by boubaker**
Set default value of wakeupInterval switch benchmarking result.

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
No need to update https://github.com/exodev/platform/blob/59d83d5f02b3127d44ec688eba447703555cc88b/extension/config/src/main/resources/conf/platform/cache/infinispan/cluster/cache-async-config.xml#L60 and https://github.com/exodev/platform/blob/59d83d5f02b3127d44ec688eba447703555cc88b/extension/config/src/main/resources/conf/platform/cache/infinispan/cluster/cache-config.xml#L51 ?

**Comment by boubaker** [comment]
Nope, only JCR caches are impacted by the default value 5 sec like 4.4

**Comment by thomasdelhomenie** [comment]
ok :+1:

**Comment by boubaker** [comment]
Outdated

**Pull request closed without merging**
